/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var wison_parser = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,14],$V1=[1,18],$V2=[13,15],$V3=[35,37],$V4=[1,29],$V5=[1,37],$V6=[1,33],$V7=[1,34],$V8=[1,35],$V9=[1,36],$Va=[33,36],$Vb=[1,43],$Vc=[1,44],$Vd=[1,45],$Ve=[19,20,21,22,24],$Vf=[1,51],$Vg=[1,50],$Vh=[19,41],$Vi=[16,19,36,41];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"program":3,"WISON":4,"WISON_OPEN":5,"lex_block":6,"syntax_block":7,"WISON_CLOSE":8,"EOF":9,"LEX":10,"LEX_OPEN":11,"terminal_decl_list":12,"LEX_CLOSE":13,"terminal_decl":14,"TERMINAL_KW":15,"TERMINAL_NAME":16,"ARROW":17,"regex_expr":18,"SEMICOLON":19,"STAR":20,"PLUS":21,"QUESTION":22,"LPAREN":23,"RPAREN":24,"LITERAL":25,"RANGE_ALPHA":26,"RANGE_DIGIT":27,"SYNTAX":28,"SYNTAX_OPEN":29,"nt_decl_list":30,"initial_decl":31,"production_list":32,"SYNTAX_CLOSE":33,"nt_decl":34,"NO_TERMINAL_KW":35,"NT_NAME":36,"INITIAL_SIM_KW":37,"production":38,"PROD_ARROW":39,"alternative_list":40,"PIPE":41,"symbol_list":42,"symbol":43,"$accept":0,"$end":1},
terminals_: {2:"error",4:"WISON",5:"WISON_OPEN",8:"WISON_CLOSE",9:"EOF",10:"LEX",11:"LEX_OPEN",13:"LEX_CLOSE",15:"TERMINAL_KW",16:"TERMINAL_NAME",17:"ARROW",19:"SEMICOLON",20:"STAR",21:"PLUS",22:"QUESTION",23:"LPAREN",24:"RPAREN",25:"LITERAL",26:"RANGE_ALPHA",27:"RANGE_DIGIT",28:"SYNTAX",29:"SYNTAX_OPEN",33:"SYNTAX_CLOSE",35:"NO_TERMINAL_KW",36:"NT_NAME",37:"INITIAL_SIM_KW",39:"PROD_ARROW",41:"PIPE"},
productions_: [0,[3,6],[3,5],[6,4],[6,3],[12,2],[12,1],[14,5],[18,2],[18,2],[18,2],[18,4],[18,3],[18,1],[18,1],[18,1],[18,1],[7,6],[30,2],[30,1],[34,3],[31,3],[32,2],[32,1],[38,4],[40,3],[40,2],[40,1],[42,2],[42,1],[43,1],[43,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
 return { terminals:$$[$0-3].terminals, nonTerminals:$$[$0-2].nonTerminals, initialSymbol:$$[$0-2].initialSymbol, productions:$$[$0-2].productions, errors:[] }; 
break;
case 2:
 return { terminals:$$[$0-2].terminals, nonTerminals:$$[$0-1].nonTerminals, initialSymbol:$$[$0-1].initialSymbol, productions:$$[$0-1].productions, errors:[] }; 
break;
case 3:
 this.$ = { terminals: $$[$0-1] }; 
break;
case 4:
 this.$ = { terminals: [] }; 
break;
case 5: case 18: case 22: case 28:
 this.$ = $$[$0-1].concat([$$[$0]]); 
break;
case 6: case 19: case 23: case 27: case 29:
 this.$ = [$$[$0]]; 
break;
case 7:
 this.$ = { name:$$[$0-3], pattern:$$[$0-1].pattern, patternType:$$[$0-1].type }; 
break;
case 8:
 this.$ = { pattern:'('+$$[$0-1].pattern+')*', type:'kleene' }; 
break;
case 9:
 this.$ = { pattern:'('+$$[$0-1].pattern+')+', type:'positive' }; 
break;
case 10:
 this.$ = { pattern:'('+$$[$0-1].pattern+')?', type:'optional' }; 
break;
case 11:
 this.$ = { pattern:$$[$0-2].pattern+$$[$0].pattern, type:'concat' }; 
break;
case 12:
 this.$ = { pattern:$$[$0-1].pattern, type:'group' }; 
break;
case 13:

            var raw = yytext.slice(1,-1);
            var esc = raw.replace(/[-[\]{}()*+?.,\\^$|#\s]/g,'\\$&');
            this.$ = { pattern:esc, type:'literal' };
        
break;
case 14:
 this.$ = { pattern:'[a-zA-Z]', type:'range' }; 
break;
case 15:
 this.$ = { pattern:'[0-9]', type:'range' }; 
break;
case 16:
 this.$ = { pattern:yytext, type:'reference' }; 
break;
case 17:
 this.$ = { nonTerminals:$$[$0-3], initialSymbol:$$[$0-2], productions:$$[$0-1] }; 
break;
case 20:
 this.$ = { name:$$[$0-1], isInitial:false }; 
break;
case 21:
 this.$ = $$[$0-1]; 
break;
case 24:
 this.$ = { head:$$[$0-3], alternatives:$$[$0-1] }; 
break;
case 25:
 this.$ = $$[$0-2].concat([$$[$0]]); 
break;
case 26:
 this.$ = $$[$0-1].concat([[]]); 
break;
case 30:
 this.$ = { name:$$[$0], type:'nonTerminal' }; 
break;
case 31:
 this.$ = { name:$$[$0], type:'terminal' }; 
break;
}
},
table: [{3:1,4:[1,2]},{1:[3]},{5:[1,3]},{6:4,10:[1,5]},{7:6,28:[1,7]},{11:[1,8]},{8:[1,9]},{29:[1,10]},{12:11,13:[1,12],14:13,15:$V0},{1:[2,2],9:[1,15]},{30:16,34:17,35:$V1},{13:[1,19],14:20,15:$V0},{28:[2,4]},o($V2,[2,6]),{16:[1,21]},{1:[2,1]},{31:22,34:23,35:$V1,37:[1,24]},o($V3,[2,19]),{36:[1,25]},{28:[2,3]},o($V2,[2,5]),{17:[1,26]},{32:27,36:$V4,38:28},o($V3,[2,18]),{36:[1,30]},{19:[1,31]},{16:$V5,18:32,23:$V6,25:$V7,26:$V8,27:$V9},{33:[1,38],36:$V4,38:39},o($Va,[2,23]),{39:[1,40]},{19:[1,41]},o($V3,[2,20]),{19:[1,42],20:$Vb,21:$Vc,22:$Vd},{16:$V5,18:46,23:$V6,25:$V7,26:$V8,27:$V9},o($Ve,[2,13]),o($Ve,[2,14]),o($Ve,[2,15]),o($Ve,[2,16]),{8:[2,17]},o($Va,[2,22]),{16:$Vf,36:$Vg,40:47,42:48,43:49},{36:[2,21]},o($V2,[2,7]),o($Ve,[2,8]),o($Ve,[2,9]),o($Ve,[2,10]),{20:$Vb,21:$Vc,22:$Vd,24:[1,52]},{19:[1,53],41:[1,54]},o($Vh,[2,27],{43:55,16:$Vf,36:$Vg}),o($Vi,[2,29]),o($Vi,[2,30]),o($Vi,[2,31]),o($Ve,[2,12],{18:56,16:$V5,23:$V6,25:$V7,26:$V8,27:$V9}),o($Va,[2,24]),o($Vh,[2,26],{43:49,42:57,16:$Vf,36:$Vg}),o($Vi,[2,28]),o($Ve,[2,11]),o($Vh,[2,25],{43:55,16:$Vf,36:$Vg})],
defaultActions: {12:[2,4],15:[2,1],19:[2,3],38:[2,17],41:[2,21]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};


if (typeof module !== 'undefined') {
    module.exports = {
        parser: parser,
        parseWison: function(source) {
            try {
                return parser.parse(source);
            } catch (e) {
                throw {
                    type: (e.message && e.message.indexOf('Parse error') !== -1)
                          ? 'syntactic' : 'lexical',
                    message: e.message || String(e),
                    line: (e.hash && e.hash.loc) ? e.hash.loc.first_line : null
                };
            }
        }
    };
}
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:
break;
case 1:
break;
case 2:
break;
case 3:return 8
break;
case 4:return 4
break;
case 5:return 5
break;
case 6:return 33
break;
case 7:return 29
break;
case 8:return 13
break;
case 9:return 11
break;
case 10:return 35
break;
case 11:return 37
break;
case 12:return 15
break;
case 13:return 28
break;
case 14:return 10
break;
case 15:return 17
break;
case 16:return 39
break;
case 17:return 26
break;
case 18:return 27
break;
case 19:return 25
break;
case 20:return 20
break;
case 21:return 21
break;
case 22:return 22
break;
case 23:return 23
break;
case 24:return 24
break;
case 25:return 41
break;
case 26:return 19
break;
case 27:return 16
break;
case 28:return 36
break;
case 29:return 36
break;
case 30:return 9
break;
case 31:
break;
}
},
rules: [/^(?:\s+)/,/^(?:[/][*][*][\s\S]*?[*][/])/,/^(?:#[^\n]*)/,/^(?:\?Wison\b)/,/^(?:Wison\b)/,/^(?:\u00bf)/,/^(?::\}\})/,/^(?:\{\{:)/,/^(?::\})/,/^(?:\{:)/,/^(?:No_Terminal\b)/,/^(?:Initial_Sim\b)/,/^(?:Terminal\b)/,/^(?:Syntax\b)/,/^(?:Lex\b)/,/^(?:<-)/,/^(?:<=)/,/^(?:\[aA-zZ\])/,/^(?:\[0-9\])/,/^(?:'([^\'\\]|\\.)*')/,/^(?:\*)/,/^(?:\+)/,/^(?:\?)/,/^(?:\()/,/^(?:\))/,/^(?:\|)/,/^(?:;)/,/^(?:\$_[a-zA-Z_][a-zA-Z0-9_]*)/,/^(?:%_[a-zA-Z_][a-zA-Z0-9_]*)/,/^(?:%[a-zA-Z_][a-zA-Z0-9_]*)/,/^(?:$)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = wison_parser;
exports.Parser = wison_parser.Parser;
exports.parse = function () { return wison_parser.parse.apply(wison_parser, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}